#!/usr/bin/bash
set -e

sudo apt-get install fastp
sudo apt-get install fastqc
sudo apt-get install bwa
sudo apt-get install samtools
sudo apt-get install bcftools

mkdir -p ~/workshop/data/untrimmed_fastq_files

#Move the raw data into untrimmed_fastq_files
cd ~/workshop/data/untrimmed_fastq_files

echo "Running FastQC ..."
fastqc *.fastq*

mkdir -p ~/workshop/results/fastqc_untrimmed_reads

echo "Saving FastQC results..."
mv *.zip ~/workshop/results/fastqc_untrimmed_reads/
mv *.html ~/workshop/results/fastqc_untrimmed_reads/

cd ~/workshop/results/fastqc_untrimmed_reads/

echo "Unzipping..."
for filename in *.zip
    do
    unzip $filename
    done

echo "Saving summary..."
cat */summary.txt > ~/workshop/docs/fastqc_summaries.txt

cd ~/dc_workshop/results


#Supply the reference genome
echo "Supply the reference genome"
read ref_genome

gunzip ref_genome

bwa index $ref_genome

mkdir -p sam bam bcf vcf

for file in ~/dc_workshop/data/trimmed_fastq_small/*_1.trim.sub.fastq
    do
    echo "working with file $fq1"
