#!/usr/bin/bash
set -e

echo "Do you have all the packages needed for variant calling installed?"
echo "Yes/No: "
read Input

if [[$Input -eq No]]
then
    do
    sudo apt-get install fastp \
    sudo apt-get install fastqc \
    sudo apt-get install bwa \
    sudo apt-get install samtools \
    sudo apt-get install bcftools \
    done
elif [[$Input -eq Yes]]
then
    echo "Let us proceed"
fi

echo "Move your untrimmed fastq files into ~/workshop/data/untrimmed_fastq_files"
echo "Using the 'mv' command like this: mv [current path of the untrimmed fastq files] ~/workshop/data/untrimmed_fastq_files"
echo "Supply the command as stated above: "
read move
echo "Moving the untrimmed fastq files"
    do
    $move
    done

#Running FastQC
cd ~/workshop/data/untrimmed_fastq_files
echo "Running FastQC ..."
fastqc *.fastq*
mkdir -p ~/workshop/results/fastqc_untrimmed_reads
echo "Saving FastQC results..."
mv *.zip ~/workshop/results/fastqc_untrimmed_reads/
mv *.html ~/workshop/results/fastqc_untrimmed_reads/

#Unzipping the fastq file
cd ~/workshop/results/fastqc_untrimmed_reads/
echo "Unzipping..."
for filename in *.zip
    do
    unzip $filename
    done
echo "Saving summary..."
cat */summary.txt > ~/workshop/docs/fastqc_summaries.txt
mkdir -p ~/workshop/data/trimmed_fastq_file/

#Running Fastp
echo "Running Fastp"
mkdir qc_reads
for f1 in *1.fastq
do
    f2=${f1%%1.fastq}"2.fastq"
  fastp \
    -i "$PWD/${f1}" \
    -I "$PWD/${f2}" \
    -o "qc_reads/$(basename ${f1%_*})_r1.trimmed.fastq" \
    -O "qc_reads/$(basename ${f2%_*})_r2.trimmed.fastq" \
    --html "qc_reads/${f1%_*}_fastp.html" 
done

mv qc_reads/ ~/workshop/data/trimmed_fastq_file/

#Variant calling

#Supply the reference genome
mkdir ~/workshop/data/ref_genome
echo "Supply the reference genome"
echo "Input the path to the reference genome: "
read ref_genome
mv $ref_genome ~/workshop/data/ref_genome

cd ~/workshop/data/ref_genome
gunzip $ref_genome
mkdir -p ~/workshop/results/sam results/bam results/bcf results/vcf

#Indexing the reference genome
bwa index $ref_genome

for file1 in ~/workshop/data/trimmed_fastq_file/*_r1.trimmed.fastq
    do
    echo "working with file $file1"

    base=$(basename $file1 _r1.trimmed.fastq)
    echo "base name is $base"

    file1=~/workshop/data/trimmed_fastq_file/${base}_r1.trimmed.fastq
    file2=~/workshop/data/trimmed_fastq_file/${base}_r2.trimmed.fastq
    sam=~/workshop/results/sam/${base}.aligned.sam
    bam=~/workshop/results/bam/${base}.aligned.bam
    sorted_bam=~/workshop/results/bam/${base}.aligned.sorted.bam
    raw_bcf=~/workshop/results/bcf/${base}_raw.bcf
    variants=~/workshop/results/vcf/${base}_variants.vcf
    final_variants=~/workshop/results/vcf/${base}_final_variants.vcf 

    bwa mem $ref_genome $file1 $file2 > $sam
    samtools view -S -b $sam > $bam
    samtools sort -o $sorted_bam $bam
    samtools index $sorted_bam
    bcftools mpileup -O b -o $raw_bcf -f $ref_genome $sorted_bam
    bcftools call --ploidy 1 -m -v -o $variants $raw_bcf 
    vcfutils.pl varFilter $variants > $final_variants
   
    done
