#! /bin/bash
set -e

echo "Do you have all the packages needed for variant calling installed?"
read -p "y = Yes/n = No: " Input

if [[ $Input = n ]]
then
    sudo apt-get install fastp 
    sudo apt-get install fastqc 
    sudo apt-get install bwa 
    sudo apt-get install samtools 
    sudo apt-get install bcftools 
else
        echo "Let us proceed";
fi

#Moving your untrimmed datasets
echo "Creating a folder..."
mkdir -p ~/workshop/data/untrimmed_fastq_files
echo "Copy your untrimmed datasets into ~/workshop/data/untrimmed_fastq_files"
echo "Input the path to the dataset: "
read move
cd $move
echo "Copying the untrimmed fastq files..."
cp *.gz ~/workshop/data/untrimmed_fastq_files
    
#Move the reference genome
mkdir ~/workshop/data/ref_genome
echo "Copy the reference genome into ~/workshop/data/ref_genome"
echo "Input the path to the reference genome: "
read ref_genome
cd $ref_genome
echo "Copying the reference genome..."
cp *.fa.gz ~/workshop/data/ref_genome

#Running FastQC
cd ~/workshop/data/untrimmed_fastq_files
echo "Running FastQC ..."
for file in *.fastq.gz
        do
        fastqc $file
        done
mkdir -p ~/workshop/results/fastqc_untrimmed_reads
echo "Saving FastQC results..."
mv *.gz ~/workshop/results/fastqc_untrimmed_reads/
mv *.html ~/workshop/results/fastqc_untrimmed_reads/

#Unzipping the fastq file
echo "Changing directory..."
cd ~/workshop/results/fastqc_untrimmed_reads/
echo "Unzipping..."
for filename in *.zip
    do
    gunzip $filename
    done
echo "Saving summary..."
mkdir -p ~/workshop/docs
mkdir -p ~/workshop/data/trimmed_fastq_file/

#Running Fastp
echo "Running Fastp..."
mkdir qc_reads
for f1 in *1.fastq
do
    f2=${f1%%1.fastq}"2.fastq"
  fastp \
    -i "$PWD/${f1}" \
    -I "$PWD/${f2}" \
    -o "qc_reads/$(basename ${f1%_*})_r1.trimmed.fastq" \
    -O "qc_reads/$(basename ${f2%_*})_r2.trimmed.fastq" \
    --html "qc_reads/${f1%_*}_fastp.html" 
done
cd qc_reads
echo "Moving trimmed files..."
mv *.trimmed.fastq ~/workshop/data/trimmed_fastq_file/

#Variant calling

echo "Variant calling..."
echo "Unzipping the reference genome"
cd ~/workshop/data/ref_genome
gunzip *.fa.gz
mkdir -p ~/workshop/results/sam results/bam results/bcf results/vcf

#Indexing the reference genome
echo "Indexing the reference genome..."
bwa index *.fa

for file1 in ~/workshop/data/trimmed_fastq_file/*_r1.trimmed.fastq
    do
    echo "working with file $file1"

    base=$(basename $file1 _r1.trimmed.fastq)
    echo "base name is $base"

    file1=~/workshop/data/trimmed_fastq_file/${base}_r1.trimmed.fastq
    file2=~/workshop/data/trimmed_fastq_file/${base}_r2.trimmed.fastq
    sam=~/workshop/results/sam/${base}.aligned.sam
    bam=~/workshop/results/bam/${base}.aligned.bam
    sorted_bam=~/workshop/results/bam/${base}.aligned.sorted.bam
    raw_bcf=~/workshop/results/bcf/${base}_raw.bcf
    variants=~/workshop/results/vcf/${base}_variants.vcf
    final_variants=~/workshop/results/vcf/${base}_final_variants.vcf 
    echo "Aligning..."
    bwa mem $ref_genome $file1 $file2 > $sam
    echo "Converting to bam ..."
    samtools view -S -b $sam > $bam
    echo "Sorting bam ..."
    samtools sort -o $sorted_bam $bam
    echo "Indexing sorted files ..."
    samtools index $sorted_bam
    bcftools mpileup -O b -o $raw_bcf -f $ref_genome $sorted_bam
    bcftools call --ploidy 1 -m -v -o $variants $raw_bcf 
    vcfutils.pl varFilter $variants > $final_variants
   
    done
